# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_auto_20170223_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestObject',
            new_name='ObjectInterest',
        ),
    ]
