# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0004_auto_20170223_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectWithInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('object_type', models.CharField(max_length=254)),
            ],
        ),
    ]
